// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANOQWhBHJw5WbpFdZi6slnNcEj8CRup6U',
    appId: '1:33957220330:web:141e66fcb824b89054ac93',
    messagingSenderId: '33957220330',
    projectId: 'cw06-ddb9f',
    authDomain: 'cw06-ddb9f.firebaseapp.com',
    storageBucket: 'cw06-ddb9f.firebasestorage.app',
    measurementId: 'G-NKSM66HLQL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqbgd6-42Ju-a0fC-oyMPJTiy6VtHlxko',
    appId: '1:33957220330:android:7edc16b257c7ee6154ac93',
    messagingSenderId: '33957220330',
    projectId: 'cw06-ddb9f',
    storageBucket: 'cw06-ddb9f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCBhfcwTFA77hRQFXF2r2B0Uekk8nCEJo',
    appId: '1:33957220330:ios:0f0f2d2380f0103254ac93',
    messagingSenderId: '33957220330',
    projectId: 'cw06-ddb9f',
    storageBucket: 'cw06-ddb9f.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication23',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCBhfcwTFA77hRQFXF2r2B0Uekk8nCEJo',
    appId: '1:33957220330:ios:0f0f2d2380f0103254ac93',
    messagingSenderId: '33957220330',
    projectId: 'cw06-ddb9f',
    storageBucket: 'cw06-ddb9f.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication23',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANOQWhBHJw5WbpFdZi6slnNcEj8CRup6U',
    appId: '1:33957220330:web:4be355985537f31b54ac93',
    messagingSenderId: '33957220330',
    projectId: 'cw06-ddb9f',
    authDomain: 'cw06-ddb9f.firebaseapp.com',
    storageBucket: 'cw06-ddb9f.firebasestorage.app',
    measurementId: 'G-6RWCB0BGZ9',
  );
}
